config-version: 2

name: 'pendo_source_integration_tests'
version: '0.1.0'

require-dbt-version: ">=0.20.0"
profile: 'integration_tests'

vars:
  pendo_source:
    pendo_schema: pendo_source_integration_tests
    
seeds:
  pendo_source_integration_tests:
    +quote_columns: "{{ true if target.type == 'redshift' else false }}"
    +column_types:
      _fivetran_synced: timestamp
    guide_event:
      +column_types:
        latitude: numeric
        longitude: numeric